export const URL_LIST = "https://api.themoviedb.org/3/discover/movie";
export const URL_SEARCH = "https://api.themoviedb.org/3/search/movie?query=";
export const URL_DETAIL = "https://api.themoviedb.org/3/movie/";
export const URL_PERSON = "https://api.themoviedb.org/3/person/";
export const URL_IMG = "https://image.tmdb.org/t/p/";
export const URL_YOUTUBE = "https://www.youtube.com/embed/";
export const URL_CAST = "/casts";
export const URL_VIDEO = "/videos";
export const IMG_SIZE_XSMALL = "w45";
export const IMG_SIZE_SMALL = "w200";
export const IMG_SIZE_NORMAL = "w500";
export const IMG_SIZE_LARGE = "w342";
export const IMG_SIZE_XL = "w1280/";
export const CAST_MAX_NUM = 5;
export const TRAILER_MAX_NUM = 3;
export const API_KEY = "?api_key=1e2951767b89ee22c5c64a04cf3e5109";
export const API_KEY_ALT = "&api_key=1e2951767b89ee22c5c64a04cf3e5109";
export const FETCH__MOVIES =
  "https://api.themoviedb.org/3/discover/movie?api_key=1e2951767b89ee22c5c64a04cf3e5109";
export const OTHER = "&language=en-US&page=1&include_adult=false";
